FROM debian:buster

RUN apt update && apt install nginx openssl -y

RUN mkdir -p /etc/ssl/private
RUN openssl req -x509 -nodes -days 365 -subj "/C=MA/ST=QC/O=Company, Inc./CN={{site_domain}}" -addext "subjectAltName=DNS:{{site_domain}}" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/private/nginx-selfsigned.crt

COPY ./conf/default.conf /etc/nginx/sites-enabled/

ENTRYPOINT ["nginx", "-g", "daemon off;"]
