# Startup installation for my servers
# Configuring and Installing all necessary packages.
---
- name: Update package cache
  apt:
    update_cache: yes

- name : Installing packages
  apt:
    name: [
      'vim',
      'ufw',
      'openssl',
      'python3-pip',
      'docker',
      'docker.io',
      'docker-compose',
    ]
    update_cache: true
    state: latest

- name: Create project directory
  file:
    path: '{{ webapp_path }}'
    state: directory
  become_user: '{{sudo_user}}'

- name: Add user to docker group
  user:
    name: '{{ sudo_user }}'
    groups: docker
    append: yes
  tags: docker_user_group

- name: Start docker service
  systemd:
    name: docker
    state: started
    enabled: true