---
- import_tasks: mariadb.yml
- import_tasks: phpmyadmin.yml
- import_tasks: wordpress.yml
- import_tasks: nginx.yml

- name: Launch containers
  docker_compose:
    project_src: '{{ webapp_path }}'
    services:
      - mariadb
      - phpmyadmin
      - wordpress
      - nginx
    state: present
