---
- name: Build nginx container
  community.docker.docker_compose:
    project_src: '{{ webapp_path }}'
    project_name: webapp
    services:
      - nginx
    build: true
    stopped: false
    state: present
