# The master playbook that automates all services
---
- name: Deploy Dockerized Services
  hosts: servers
  gather_facts: true
  vars_files:
    - 'vault.yml'  


  roles:
    - config
    - mariadb
    - phpmyadmin
    - wordpress
    - nginx
    - deploy