# The master playbook that automates all services
---
- name: Deploy Dockerized Services
  hosts: servers
  remote_user: '{{ sudo_user }}'
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - 'vault.yml'


  roles:
    - config
    - mariadb
    - phpmyadmin
    - wordpress
    - nginx
    - deploy