---
- name: Build mariadb container
  community.docker.docker_compose:
    project_src: '{{ webapp_path }}'
    project_name: webapp
    services:
      - mariadb
    build: true
    stopped: false
    state: present
  