# Startup installation for my servers
# Configuring and Installing all necessary packages.
---
- name: Update package cache
  apt:
    update_cache: yes

- name : Installing packages
  apt:
    name: [
      'vim',
      'ufw',
      'openssl',
      'python3-pip',
      'docker',
      'docker.io',
      'docker-compose',
    ]
    update_cache: true
    state: latest

- name: Create project directory
  file:
    path: '{{ webapp_path }}'
    state: directory
  become_user: '{{sudo_user}}'

- name: Add user to docker group
  user:
    name: '{{ sudo_user }}'
    groups: docker
    append: yes
  tags: docker_user_group

- name: Start docker service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Enable UFW
  ufw:
    state: enabled

- name: Configure UFW to start on boot
  lineinfile:
    path: /etc/ufw/ufw.conf
    regexp: '^ENABLED='
    line: 'ENABLED=yes'

- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: 22

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: 80

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    port: 443

- name: Deny all incoming traffic
  ufw:
    rule: deny

- name: Enable UFW to enforce changes
  ufw:
    state: enabled

- import_tasks: compose-configure.yml