---
- name: Maintaining individual all stoping
  hosts: servers
  gather_facts: true
  vars_files:
    - 'vault.yml'
  tasks:
    - name: Start all containers
      community.docker.docker_compose:
        project_src: '{{ webapp_path }}'
        project_name: webapp
        build: false
        stopped: false
        state: present
  