---
- name: Maintaining individual all starting
  hosts: servers
  remote_user: '{{ sudo_user }}'
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - '../vault.yml'

  tasks:
    - name: Start {{ container_name }} container
      community.docker.docker_compose:
        project_src: '{{ webapp_path }}'
        project_name: webapp
        services:
          - '{{ container_name }}'
        build: false
        stopped: false
        state: present