---
- name: Maintaining individual all stoping
  hosts: servers
  remote_user: '{{ sudo_user }}'
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - '../vault.yml'

  tasks:
    - name: Check if all containers are stoped, stop them if not
      community.docker.docker_compose:
        project_src: '{{ webapp_path }}'
        project_name: webapp
        services:
          - '{{ item }}'
        build: false
        stopped: true
        state: present
      loop:
        - mariadb
        - wordpress
        - phpmyadmin
        - nginx